# permissions for end users to edit tidbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tidbcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: api-service
    app.kubernetes.io/part-of: api-service
    app.kubernetes.io/managed-by: kustomize
  name: tidbcluster-editor-role
rules:
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters/status
  verbs:
  - get
