# permissions for end users to view tidbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tidbcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: api-service
    app.kubernetes.io/part-of: api-service
    app.kubernetes.io/managed-by: kustomize
  name: tidbcluster-viewer-role
rules:
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters/status
  verbs:
  - get
